// Catálogo Red Motos — 5 marcas oficiales (ProMobility Bikes, lista 2026).
// Precios: los legibles de la planilla. Los modelos sin foto transparente
// usan /motos/placeholder.png temporalmente (se reemplazan por la foto real).
// bonoVence null mientras no haya fecha de campaña.

import type { Moto, Marca } from "./tipos";

const PH = "/motos/placeholder.png";

export const CATALOGO: Moto[] = [
  // ── ROYAL ENFIELD ────────────────────────────────────────────────────
  {
    id: "re-hunter-350",
    marca: "Royal Enfield",
    modelo: "Hunter 350",
    segmento: "Urbana",
    cc: 349,
    precioLista: 3_499_900,
    precioBono: 3_299_900,
    bonoVence: null,
    img: "/motos/kie/re-hunter-350.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 0,
  },
  {
    id: "re-classic-350",
    marca: "Royal Enfield",
    modelo: "Classic 350",
    segmento: "Cruiser",
    cc: 349,
    precioLista: 3_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-classic-350.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 1,
  },
  {
    id: "re-classic-350-goan",
    marca: "Royal Enfield",
    modelo: "Classic 350 (Goan)",
    segmento: "Cruiser",
    cc: 349,
    precioLista: 4_399_900,
    precioBono: 4_249_900,
    bonoVence: null,
    img: "/motos/kie/re-classic-350-goan.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 2,
  },
  {
    id: "re-meteor-350-fireball",
    marca: "Royal Enfield",
    modelo: "Meteor 350 (Fireball)",
    segmento: "Cruiser",
    cc: 349,
    precioLista: 3_899_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-meteor-350.png",
    usos: ["Ciudad", "Ruta", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 3,
  },
  {
    id: "re-meteor-350-stellar",
    marca: "Royal Enfield",
    modelo: "Meteor 350 (Stellar-Supernova-Aurora)",
    segmento: "Cruiser",
    cc: 349,
    precioLista: 3_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-meteor-350.png",
    usos: ["Ciudad", "Ruta", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 4,
  },
  {
    id: "re-meteor-350-sundowner",
    marca: "Royal Enfield",
    modelo: "Meteor 350 (Sundowner Orange)",
    segmento: "Cruiser",
    cc: 349,
    precioLista: 4_499_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-meteor-350.png",
    usos: ["Ciudad", "Ruta", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 5,
  },
  {
    id: "re-grr-450",
    marca: "Royal Enfield",
    modelo: "Guerrilla 450 (GRR)",
    segmento: "Naked",
    cc: 452,
    precioLista: 5_249_900,
    precioBono: 4_999_900,
    bonoVence: null,
    img: PH,
    usos: ["Ciudad", "Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 6,
  },
  {
    id: "re-himalayan-452",
    marca: "Royal Enfield",
    modelo: "Himalayan 452",
    segmento: "Adventure",
    cc: 452,
    precioLista: 5_499_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-himalayan-452.png",
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 7,
  },
  {
    id: "re-himalayan-452-tubular",
    marca: "Royal Enfield",
    modelo: "Himalayan 452 (Tubular)",
    segmento: "Adventure",
    cc: 452,
    precioLista: 5_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-himalayan-452.png",
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 8,
  },
  {
    id: "re-himalayan-452-rally",
    marca: "Royal Enfield",
    modelo: "Himalayan 452 (Rally)",
    segmento: "Adventure",
    cc: 452,
    precioLista: 6_199_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-himalayan-452.png",
    usos: ["Off-road", "Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 9,
  },
  {
    id: "re-classic-650",
    marca: "Royal Enfield",
    modelo: "Classic 650",
    segmento: "Cruiser",
    cc: 648,
    precioLista: 6_599_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-classic-650.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 10,
  },
  {
    id: "re-classic-650-chrome",
    marca: "Royal Enfield",
    modelo: "Classic 650 (Chrome)",
    segmento: "Cruiser",
    cc: 648,
    precioLista: 6_799_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-classic-650.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 11,
  },
  {
    id: "re-shotgun-650",
    marca: "Royal Enfield",
    modelo: "Shotgun 650",
    segmento: "Custom",
    cc: 648,
    precioLista: 6_799_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-shotgun-650.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 12,
  },
  {
    id: "re-bear-650",
    marca: "Royal Enfield",
    modelo: "Bear 650",
    segmento: "Scrambler",
    cc: 648,
    precioLista: 6_599_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-bear-650.png",
    usos: ["Ciudad", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 13,
  },
  {
    id: "re-super-meteor-650-astral",
    marca: "Royal Enfield",
    modelo: "Super Meteor 650 (Astral)",
    segmento: "Cruiser",
    cc: 648,
    precioLista: 6_599_900,
    precioBono: 6_499_900,
    bonoVence: null,
    img: "/motos/kie/re-super-meteor-astral.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 14,
  },
  {
    id: "re-super-meteor-650-interestellar",
    marca: "Royal Enfield",
    modelo: "Super Meteor 650 (Interestellar)",
    segmento: "Cruiser",
    cc: 648,
    precioLista: 6_799_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-super-meteor-interestellar.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 15,
  },
  {
    id: "re-super-meteor-650-celestial",
    marca: "Royal Enfield",
    modelo: "Super Meteor 650 (Celestial)",
    segmento: "Cruiser",
    cc: 648,
    precioLista: 6_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/re-super-meteor-celestial.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: true,
    orden: 16,
  },

  // ── SUZUKI ───────────────────────────────────────────────────────────
  {
    id: "sz-burgman-street-125",
    marca: "Suzuki",
    modelo: "Burgman Street 125",
    segmento: "Scooter",
    cc: 125,
    precioLista: 2_299_900,
    precioBono: 2_199_900,
    bonoVence: null,
    img: PH,
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 17,
  },
  {
    id: "sz-gsx-150-frf-gixxer",
    marca: "Suzuki",
    modelo: "GSX 150 FRF Gixxer",
    segmento: "Naked",
    cc: 150,
    precioLista: 2_799_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/FI150A.png",
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 18,
  },
  {
    id: "sz-gsx-150-rf-gixxer",
    marca: "Suzuki",
    modelo: "GSX 150 RF Gixxer",
    segmento: "Naked",
    cc: 150,
    precioLista: 2_599_900,
    precioBono: 2_499_900,
    bonoVence: null,
    img: "/motos/kie/DI150.png",
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 19,
  },
  {
    id: "sz-gsx250fi-gixxer",
    marca: "Suzuki",
    modelo: "GSX250FI Gixxer",
    segmento: "Deportiva",
    cc: 250,
    precioLista: 4_299_900,
    precioBono: 4_099_900,
    bonoVence: null,
    img: "/motos/kie/DI250.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 20,
  },
  {
    id: "sz-gsx250di-gixxer",
    marca: "Suzuki",
    modelo: "GSX250DI Gixxer",
    segmento: "Deportiva",
    cc: 250,
    precioLista: 3_749_900,
    precioBono: 3_549_900,
    bonoVence: null,
    img: "/motos/kie/DI250.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 21,
  },
  {
    id: "sz-gsx-8s",
    marca: "Suzuki",
    modelo: "GSX-8S",
    segmento: "Naked",
    cc: 776,
    precioLista: 10_499_900,
    precioBono: 9_499_900,
    bonoVence: null,
    img: PH,
    usos: ["Ciudad", "Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 22,
  },
  {
    id: "sz-gsx-s1000",
    marca: "Suzuki",
    modelo: "GSX-S1000",
    segmento: "Naked",
    cc: 999,
    precioLista: 14_999_900,
    precioBono: 14_499_900,
    bonoVence: null,
    img: PH,
    usos: ["Placer", "Ruta"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 23,
  },
  {
    id: "sz-gsx-r1000r",
    marca: "Suzuki",
    modelo: "GSX-R1000R",
    segmento: "Deportiva",
    cc: 999,
    precioLista: 19_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/GSX-R1000R.png",
    usos: ["Placer", "Ruta"],
    aptaPrincipiante: false,
    destacado: true,
    orden: 24,
  },
  {
    id: "sz-gsx1300ra-hayabusa",
    marca: "Suzuki",
    modelo: "GSX1300RA Hayabusa",
    segmento: "Deportiva",
    cc: 1340,
    precioLista: 20_499_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Placer", "Ruta"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 25,
  },
  {
    id: "sz-vstrom-ds250-sx",
    marca: "Suzuki",
    modelo: "V-Strom DS-250 SX",
    segmento: "Adventure",
    cc: 250,
    precioLista: 4_449_000,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/VSTROM250.png",
    usos: ["Ruta", "Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 26,
  },
  {
    id: "sz-vstrom-dl650xa",
    marca: "Suzuki",
    modelo: "V-Strom DL-650XA",
    segmento: "Adventure",
    cc: 645,
    precioLista: 10_399_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 27,
  },
  {
    id: "sz-vstrom-dl800-de",
    marca: "Suzuki",
    modelo: "V-Strom DL-800 DE",
    segmento: "Adventure",
    cc: 776,
    precioLista: 12_999_900,
    precioBono: 11_699_900,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 28,
  },
  {
    id: "sz-vstrom-dl1050-de",
    marca: "Suzuki",
    modelo: "V-Strom DL-1050 DE",
    segmento: "Adventure",
    cc: 1037,
    precioLista: 14_749_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 29,
  },
  {
    id: "sz-dr125l",
    marca: "Suzuki",
    modelo: "DR125L",
    segmento: "Off-road",
    cc: 125,
    precioLista: 2_999_000,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Ciudad"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 30,
  },
  {
    id: "sz-rmz250",
    marca: "Suzuki",
    modelo: "RM-Z250",
    segmento: "Motocross",
    cc: 249,
    precioLista: 7_999_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 31,
  },
  {
    id: "sz-rmz450",
    marca: "Suzuki",
    modelo: "RM-Z450",
    segmento: "Motocross",
    cc: 449,
    precioLista: 8_599_900,
    precioBono: 7_599_900,
    bonoVence: null,
    img: PH,
    usos: ["Off-road"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 32,
  },
  {
    id: "sz-ltf-400-fsm3",
    marca: "Suzuki",
    modelo: "LT-F 400 FSM3",
    segmento: "ATV",
    cc: 376,
    precioLista: 9_790_000,
    precioBono: 9_390_000,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 33,
  },
  {
    id: "sz-lta-900xpm3",
    marca: "Suzuki",
    modelo: "LT-A 900XPM3",
    segmento: "ATV",
    cc: 900,
    precioLista: 11_390_000,
    precioBono: 10_990_000,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 34,
  },
  {
    id: "sz-lta-750xpm3",
    marca: "Suzuki",
    modelo: "LT-A 750XPM3",
    segmento: "ATV",
    cc: 722,
    precioLista: 12_790_000,
    precioBono: 12_390_000,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 35,
  },

  // ── CYCLONE ──────────────────────────────────────────────────────────
  {
    id: "cy-ra2",
    marca: "Cyclone",
    modelo: "RA2",
    segmento: "Naked",
    cc: 250,
    precioLista: 2_899_900,
    precioBono: 2_699_900,
    bonoVence: null,
    img: "/motos/kie/RA2.png",
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: true,
    orden: 36,
  },
  {
    id: "cy-rx-401",
    marca: "Cyclone",
    modelo: "RX-401",
    segmento: "Adventure",
    cc: 401,
    precioLista: 5_899_990,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 37,
  },
  {
    id: "cy-rx-401-maletas",
    marca: "Cyclone",
    modelo: "RX-401 con Maletas",
    segmento: "Adventure",
    cc: 401,
    precioLista: 6_199_990,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 38,
  },
  {
    id: "cy-rx1",
    marca: "Cyclone",
    modelo: "RX1",
    segmento: "Adventure",
    cc: 401,
    precioLista: 6_199_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Off-road", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 39,
  },

  // ── ZONSEN (Zongshen) ────────────────────────────────────────────────
  {
    id: "zs-zii",
    marca: "Zonsen",
    modelo: "ZII",
    segmento: "Naked",
    cc: 200,
    precioLista: 1_899_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 40,
  },
  {
    id: "zs-rx3",
    marca: "Zonsen",
    modelo: "RX3",
    segmento: "Adventure",
    cc: 250,
    precioLista: 3_599_900,
    precioBono: 3_099_900,
    bonoVence: null,
    img: PH,
    usos: ["Ruta", "Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: true,
    orden: 41,
  },

  // ── KYMCO ────────────────────────────────────────────────────────────
  {
    id: "ky-xtown-300",
    marca: "Kymco",
    modelo: "X-Town 300",
    segmento: "Scooter",
    cc: 300,
    precioLista: 3_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/kie/xtown300.png",
    usos: ["Ciudad", "Trabajo", "Ruta"],
    aptaPrincipiante: true,
    destacado: true,
    orden: 42,
  },
  {
    id: "ky-mxu-150",
    marca: "Kymco",
    modelo: "MXU 150",
    segmento: "ATV",
    cc: 150,
    precioLista: 3_899_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 43,
  },
  {
    id: "ky-mxu-250",
    marca: "Kymco",
    modelo: "MXU 250",
    segmento: "ATV",
    cc: 250,
    precioLista: 4_799_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 44,
  },
  {
    id: "ky-mxu-300r",
    marca: "Kymco",
    modelo: "MXU 300R",
    segmento: "ATV",
    cc: 300,
    precioLista: 5_499_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 45,
  },
  {
    id: "ky-uxv-450",
    marca: "Kymco",
    modelo: "UXV 450",
    segmento: "UTV",
    cc: 443,
    precioLista: 10_999_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 46,
  },
  {
    id: "ky-uxv-700ia",
    marca: "Kymco",
    modelo: "UXV 700iA",
    segmento: "UTV",
    cc: 695,
    precioLista: 12_599_900,
    precioBono: null,
    bonoVence: null,
    img: PH,
    usos: ["Off-road", "Trabajo"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 47,
  },
];

/** Marcas presentes en el catálogo, en orden de jerarquía comercial. */
export const MARCAS_CATALOGO: Marca[] = [
  "Royal Enfield",
  "Suzuki",
  "Kymco",
  "Zonsen",
  "Cyclone",
];

/** Marcas distribuidas oficialmente (para el marquee de logos). */
export const MARCAS_OFICIALES = [
  { nombre: "Royal Enfield", logo: "/logos/logo-royal-enfield.png", insignia: true },
  { nombre: "Suzuki", logo: "/logos/logo-suzuki.png", insignia: true },
  { nombre: "Kymco", logo: "/logos/logo-kymco.png", insignia: false },
] as const;

export const MOTOS_ROYAL_ENFIELD = CATALOGO.filter(
  (m) => m.marca === "Royal Enfield",
);
export const MOTOS_SUZUKI = CATALOGO.filter((m) => m.marca === "Suzuki");

/** Precio vigente de una moto (bono si existe, lista si no). */
export function precioVigente(moto: Moto): number {
  return moto.precioBono ?? moto.precioLista;
}
