// Catálogo REAL de Red Motos — datos scrapeados de redmotos.cl (2026-06-09).
// 17 modelos con precios reales publicados. Los precios con bono traen
// precioLista (tachado) + precioBono (final). NO inventar cifras: los modelos
// que faltan del stock se agregan aquí cuando el cliente entregue sus precios.

import type { Moto, Marca } from "./tipos";

export const CATALOGO: Moto[] = [
  // ── ROYAL ENFIELD ────────────────────────────────────────────────────
  {
    id: "re-hunter-350",
    marca: "Royal Enfield",
    modelo: "Hunter 350",
    segmento: "Urbana",
    cc: 350,
    precioLista: 3_499_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/Hunter350.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: true,
    orden: 0,
  },
  {
    id: "re-super-meteor-650-astral",
    marca: "Royal Enfield",
    modelo: "Super Meteor 650 Astral",
    segmento: "Cruiser",
    cc: 650,
    precioLista: 6_799_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/ASTRALBLUE.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: true,
    orden: 1,
  },
  {
    id: "re-super-meteor-650-interestellar",
    marca: "Royal Enfield",
    modelo: "Super Meteor 650 Interestellar",
    segmento: "Cruiser",
    cc: 650,
    precioLista: 6_899_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/INTERESTELLARGREEN.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 2,
  },
  {
    id: "re-super-meteor-650-celestial",
    marca: "Royal Enfield",
    modelo: "Super Meteor 650 Celestial",
    segmento: "Cruiser",
    cc: 650,
    precioLista: 6_999_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/CELESTIALRED.png",
    usos: ["Ruta", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 3,
  },
  {
    id: "re-scram-411",
    marca: "Royal Enfield",
    modelo: "Scram 411",
    segmento: "Scrambler",
    cc: 411,
    precioLista: 4_599_900,
    precioBono: 4_299_900,
    bonoVence: null,
    img: "/motos/SCRAM.411.png",
    usos: ["Ciudad", "Off-road", "Placer"],
    aptaPrincipiante: true,
    destacado: true,
    orden: 4,
  },
  {
    id: "re-shotgun-650",
    marca: "Royal Enfield",
    modelo: "Shotgun 650",
    segmento: "Custom",
    cc: 650,
    precioLista: 6_599_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/SHOTGUN650.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 5,
  },

  // ── SUZUKI ───────────────────────────────────────────────────────────
  {
    id: "sz-gixxer-150-fi",
    marca: "Suzuki",
    modelo: "Gixxer 150 FI",
    segmento: "Naked",
    cc: 150,
    precioLista: 2_799_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/FI150A.png",
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 6,
  },
  {
    id: "sz-gixxer-150-di",
    marca: "Suzuki",
    modelo: "Gixxer 150 DI",
    segmento: "Naked",
    cc: 150,
    precioLista: 2_499_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/DI150.png",
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 7,
  },
  {
    id: "sz-gixxer-250-di",
    marca: "Suzuki",
    modelo: "Gixxer 250 DI",
    segmento: "Deportiva",
    cc: 250,
    precioLista: 3_749_900,
    precioBono: null,
    bonoVence: null,
    img: "/motos/DI250.png",
    usos: ["Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: true,
    orden: 8,
  },
  {
    id: "sz-vstrom-250",
    marca: "Suzuki",
    modelo: "V-Strom 250",
    segmento: "Adventure",
    cc: 250,
    precioLista: 4_449_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/VSTROM250.png",
    usos: ["Ruta", "Ciudad", "Placer"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 9,
  },
  {
    id: "sz-gsx-r-1000r",
    marca: "Suzuki",
    modelo: "GSX-R 1000R",
    segmento: "Deportiva",
    cc: 1000,
    precioLista: 19_999_990,
    precioBono: null,
    bonoVence: null,
    img: "/motos/GSX-R1000R.png",
    usos: ["Placer", "Ruta"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 10,
  },

  // ── KYMCO ────────────────────────────────────────────────────────────
  {
    id: "ky-xtown-300",
    marca: "Kymco",
    modelo: "X-Town 300",
    segmento: "Scooter",
    cc: 300,
    precioLista: 4_599_990,
    precioBono: 3_999_990,
    bonoVence: null,
    img: "/motos/xtown300.png",
    usos: ["Ciudad", "Trabajo", "Ruta"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 11,
  },

  // ── ZONTES ───────────────────────────────────────────────────────────
  {
    id: "zt-zt350-t2",
    marca: "Zontes",
    modelo: "ZT350-T2",
    segmento: "Adventure",
    cc: 350,
    precioLista: 4_390_000,
    precioBono: null,
    bonoVence: null,
    img: "/motos/T2.350.png",
    usos: ["Ruta", "Ciudad", "Placer"],
    aptaPrincipiante: false,
    destacado: false,
    orden: 13,
  },

  // ── CYCLONE ──────────────────────────────────────────────────────────
  {
    id: "cy-ra2",
    marca: "Cyclone",
    modelo: "RA2",
    segmento: "Naked",
    cc: 250,
    precioLista: 2_899_900,
    precioBono: 2_699_900,
    bonoVence: null,
    img: "/motos/RA2.png",
    usos: ["Ciudad", "Trabajo"],
    aptaPrincipiante: true,
    destacado: false,
    orden: 16,
  },
];

/** Marcas presentes en el catálogo, en orden de jerarquía comercial. */
export const MARCAS_CATALOGO: Marca[] = [
  "Royal Enfield",
  "Suzuki",
  "Kymco",
  "Zontes",
  "Cyclone",
];

/** Marcas distribuidas oficialmente (para el marquee de logos). */
export const MARCAS_OFICIALES = [
  { nombre: "Royal Enfield", logo: "/logos/logo-royal-enfield.png", insignia: true },
  { nombre: "Suzuki", logo: "/logos/logo-suzuki.png", insignia: true },
  { nombre: "Kymco", logo: "/logos/logo-kymco.png", insignia: false },
] as const;

export const MOTOS_ROYAL_ENFIELD = CATALOGO.filter(
  (m) => m.marca === "Royal Enfield",
);
export const MOTOS_SUZUKI = CATALOGO.filter((m) => m.marca === "Suzuki");

/** Precio vigente de una moto (bono si existe, lista si no). */
export function precioVigente(moto: Moto): number {
  return moto.precioBono ?? moto.precioLista;
}
