// Fichas técnicas por modelo, keyed por `moto.id` (ver lib/catalogo.ts).
// Datos SOLO en código — no toca Supabase ni admin.
//
// Fuente de specs numéricas: hojas técnicas oficiales del fabricante.
//   · Royal Enfield → royalenfield.com (PDFs de especificaciones).
// Regla: si un dato no se encuentra o la fuente lo entrega corrupto, queda como
// "—" (nunca se inventan cifras). La UI muestra "—" de forma tenue.
//
// Las variantes de un mismo modelo (colores/ediciones) comparten specs mecánicas
// vía spread de un objeto base; solo cambian `colores` y, a veces, `descripcion`.

export type FichaTecnica = {
  descripcion: string;
  destacados: string[];
  motor: string;
  cilindrada: string;
  potencia: string;
  torque: string;
  transmision: string;
  frenos: string;
  abs: string;
  suspensionDel: string;
  suspensionTras: string;
  neumaticoDel: string;
  neumaticoTras: string;
  largo?: string;
  alturaAsiento: string;
  peso: string;
  estanque: string;
  colores: string[];
};

const DATO_FALTANTE = "—";

// ─── Bases reutilizables (Royal Enfield) ─────────────────────────────────────

// Motor J 350 (Hunter / Classic / Meteor) comparte arquitectura, varía chasis.
const meteor350Base: Omit<FichaTecnica, "descripcion" | "destacados" | "colores"> = {
  motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire/aceite (motor J)",
  cilindrada: "349 cc",
  potencia: "20,2 hp @ 6.100 rpm",
  torque: "27 Nm @ 4.000 rpm",
  transmision: "5 velocidades, engrane constante",
  frenos: "Disco 300 mm delantero (pinza flotante 2 pistones) · Disco 270 mm trasero",
  abs: "Doble canal",
  suspensionDel: "Telescópica, barras de 41 mm",
  suspensionTras: "Amortiguadores gemelos con precarga ajustable (6 pasos)",
  neumaticoDel: "100/90-19 (tubeless)",
  neumaticoTras: "140/70-17 (tubeless)",
  largo: "2.140 mm",
  alturaAsiento: "765 mm",
  peso: "191 kg",
  estanque: "15 L",
};

const himalayan452Base: Omit<FichaTecnica, "descripcion" | "destacados" | "colores"> = {
  motor: "Monocilíndrico, refrigerado por líquido, DOHC, 4 válvulas (Sherpa 450)",
  cilindrada: "452 cc",
  potencia: "40 hp @ 8.000 rpm",
  torque: "40 Nm @ 5.500 rpm",
  transmision: "6 velocidades",
  frenos: DATO_FALTANTE,
  abs: "Conmutable (switchable)",
  suspensionDel: "Horquilla invertida de 43 mm, largo recorrido",
  suspensionTras: "Monoamortiguador con sistema de bieletas",
  neumaticoDel: "90/90-21",
  neumaticoTras: DATO_FALTANTE,
  largo: "2.245 mm",
  alturaAsiento: "825 mm (ajustable a 845 mm)",
  peso: "196 kg",
  estanque: "17 L",
};

const classic650Base: Omit<FichaTecnica, "descripcion" | "destacados" | "colores"> = {
  motor: "Bicilíndrico en línea, 4T, SOHC, refrigerado por aire/aceite",
  cilindrada: "648 cc",
  potencia: "47 hp @ 7.250 rpm (34,6 kW)",
  torque: "52,3 Nm @ 5.650 rpm",
  transmision: "6 velocidades, engrane constante",
  frenos: "Disco 320 mm delantero (2 pistones) · Disco 300 mm trasero (2 pistones)",
  abs: "Doble canal",
  suspensionDel: "Horquilla telescópica de 43 mm",
  suspensionTras: "Doble amortiguador",
  neumaticoDel: "100/90-19",
  neumaticoTras: "140/70 R18",
  largo: "2.318 mm",
  alturaAsiento: "800 mm",
  peso: "243 kg",
  estanque: "14,8 L",
};

const superMeteor650Base: Omit<FichaTecnica, "descripcion" | "destacados" | "colores"> = {
  motor: "Bicilíndrico en paralelo, 4T, SOHC, refrigerado por aire/aceite",
  cilindrada: "648 cc",
  potencia: "47 hp @ 7.250 rpm (34,6 kW)",
  torque: "52,3 Nm @ 5.650 rpm",
  transmision: "6 velocidades, engrane constante",
  frenos: "Disco 320 mm delantero (2 pistones) · Disco 300 mm trasero (2 pistones)",
  abs: "Doble canal",
  suspensionDel: "Horquilla invertida de 43 mm, 120 mm de recorrido",
  suspensionTras: "Doble amortiguador, 101 mm, precarga ajustable",
  neumaticoDel: "100/90-19 (tubeless)",
  neumaticoTras: "150/80 B16 (tubeless)",
  largo: "2.260 mm",
  // Fuente entregó 890 mm "sin espejos" (altura total, no del asiento) → se deja
  // pendiente de verificación para no publicar un dato erróneo.
  alturaAsiento: DATO_FALTANTE,
  peso: "241 kg",
  estanque: "15,7 L",
};

const meteorDestacados = [
  "Asiento bajo de 765 mm, fácil de pisar",
  "Motor J de 349 cc, suave y tractable",
  "Navegación Tripper incluida",
  "Postura crucero relajada",
  "Frenos de disco con ABS de doble canal",
];

const himalayanDestacados = [
  "Motor Sherpa 450 refrigerado por líquido, 40 hp",
  "Rueda delantera de 21'' para off-road",
  "Suspensión invertida de 43 mm de largo recorrido",
  "Altura de asiento ajustable",
  "Pantalla circular TFT con Google Maps",
];

// ─── FICHAS ──────────────────────────────────────────────────────────────────
export const FICHAS: Record<string, FichaTecnica> = {
  // ── ROYAL ENFIELD ──────────────────────────────────────────────────────────
  "re-hunter-350": {
    descripcion:
      "La Hunter 350 es la roadster urbana de Royal Enfield: compacta, ágil y con el carácter del motor J de 349 cc. Pensada para moverse rápido en ciudad sin perder el estilo clásico de la marca.",
    destacados: [
      "Motor J de 349 cc con entrega suave y torque a bajas vueltas",
      "Manejo ágil y liviano, ideal para ciudad",
      "Frenos de disco con ABS de doble canal",
      "Postura de manejo erguida y cómoda",
      "Estética roadster moderna sobre base clásica",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire/aceite (motor J)",
    cilindrada: "349 cc",
    potencia: "20,2 hp @ 6.100 rpm",
    torque: "27 Nm @ 4.000 rpm",
    transmision: "5 velocidades, engrane constante",
    frenos: "Disco 300 mm delantero (pinza flotante 2 pistones) · Disco 270 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica, barras de 41 mm, 130 mm de recorrido",
    suspensionTras: "Amortiguadores gemelos con precarga ajustable (6 pasos), 100 mm",
    neumaticoDel: "110/70-17 (tubeless)",
    neumaticoTras: "140/70-17 (tubeless)",
    largo: "2.055 mm",
    alturaAsiento: "790 mm",
    peso: "181 kg",
    estanque: "13 L",
    colores: [],
  },

  "re-classic-350": {
    descripcion:
      "La Classic 350 es el ícono retro de Royal Enfield: líneas atemporales heredadas de la G2 de 1950 y el inconfundible latido del motor J de 349 cc.",
    destacados: [
      "Diseño clásico atemporal",
      "Motor J de 349 cc, suave y tractable",
      "ABS de doble canal",
      "Amplia gama de colores",
      "Tablero analógico con asistente Tripper opcional",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire/aceite (motor J)",
    cilindrada: "349 cc",
    potencia: "20,2 hp @ 6.100 rpm",
    torque: "27 Nm @ 4.000 rpm",
    transmision: "5 velocidades, engrane constante",
    frenos: "Disco 300 mm delantero · Disco 270 mm / tambor 153 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica, barras de 41 mm, 130 mm de recorrido",
    suspensionTras: "Amortiguadores gemelos con precarga ajustable (6 pasos)",
    neumaticoDel: "100/90-19",
    neumaticoTras: "120/80-18",
    largo: "2.145 mm",
    alturaAsiento: "805 mm",
    peso: "195 kg",
    estanque: "13 L",
    colores: [
      "Chrome Red",
      "Chrome Bronze",
      "Dark Stealth Black",
      "Halcyon Green",
      "Signals Marsh Grey",
      "Dark Gunmetal Grey",
      "Signals Desert Sand",
      "Halcyon Black",
      "Halcyon Grey",
    ],
  },

  "re-classic-350-goan": {
    descripcion:
      "Edición Goan Classic de la Classic 350: la misma base mecánica del motor J de 349 cc con una paleta de colores inspirada en la costa, llantas de aleación y detalles cromados.",
    destacados: [
      "Edición especial Goan Classic",
      "Motor J de 349 cc, suave y tractable",
      "Llantas de aleación y acabados cromados",
      "ABS de doble canal",
      "Estilo clásico con identidad propia",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire/aceite (motor J)",
    cilindrada: "349 cc",
    potencia: "20,2 hp @ 6.100 rpm",
    torque: "27 Nm @ 4.000 rpm",
    transmision: "5 velocidades, engrane constante",
    frenos: "Disco 300 mm delantero · Disco 270 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica, barras de 41 mm, 130 mm de recorrido",
    suspensionTras: "Amortiguadores gemelos con precarga ajustable (6 pasos)",
    neumaticoDel: "100/90-19",
    neumaticoTras: "120/80-18",
    largo: "2.145 mm",
    alturaAsiento: "805 mm",
    peso: "195 kg",
    estanque: "13 L",
    colores: [],
  },

  "re-meteor-350-fireball": {
    ...meteor350Base,
    descripcion:
      "La Meteor 350 Fireball es la cruiser de acceso de Royal Enfield en su versión monocolor: postura relajada, asiento bajo de 765 mm y el suave motor J de 349 cc.",
    destacados: meteorDestacados,
    colores: ["Fireball Black", "Fireball Blue", "Fireball Green"],
  },

  "re-meteor-350-stellar": {
    ...meteor350Base,
    descripcion:
      "La Meteor 350 Stellar suma esquema bicolor y navegación Tripper a la cruiser de 349 cc, manteniendo el asiento bajo y la conducción relajada.",
    destacados: meteorDestacados,
    colores: ["Stellar Blue", "Stellar Black"],
  },

  "re-meteor-350-sundowner": {
    ...meteor350Base,
    descripcion:
      "La Meteor 350 Sundowner es la versión tope de gama de la cruiser de 349 cc, con la mejor terminación y equipamiento de la familia Meteor.",
    destacados: meteorDestacados,
    colores: [],
  },

  "re-grr-450": {
    descripcion:
      "La Guerrilla 450 es una roadster de media cilindrada sobre la plataforma Sherpa 450: 40 hp, chasis ágil y actitud urbana para quienes buscan una Royal Enfield moderna y divertida.",
    destacados: [
      "Motor Sherpa 450 refrigerado por líquido, 40 hp",
      "Caja de 6 velocidades",
      "Chasis ágil pensado para ciudad",
      "Tablero con conectividad",
      "Frenos de disco ventilados",
    ],
    motor: "Monocilíndrico, refrigerado por líquido, DOHC, 4 válvulas (Sherpa 450)",
    cilindrada: "452 cc",
    potencia: "40 hp @ 8.000 rpm",
    torque: "40 Nm @ 5.500 rpm",
    transmision: "6 velocidades",
    frenos: "Disco ventilado 310 mm delantero (2 pistones) · Disco ventilado 270 mm trasero",
    abs: DATO_FALTANTE,
    suspensionDel: "Horquilla telescópica de 43 mm",
    suspensionTras: "Monoamortiguador con sistema de bieletas",
    neumaticoDel: "120/70-17",
    neumaticoTras: "160/60-17",
    largo: "2.090 mm",
    alturaAsiento: "780 mm",
    peso: "185 kg",
    estanque: DATO_FALTANTE,
    colores: ["Flash", "Yellow Ribbon", "Dash", "Analogue"],
  },

  "re-himalayan-452": {
    ...himalayan452Base,
    descripcion:
      "La Himalayan 452 es la adventure de Royal Enfield: motor Sherpa 450 de 40 hp, suspensiones de largo recorrido y rueda delantera de 21'' para salir del asfalto con confianza.",
    destacados: himalayanDestacados,
    colores: [],
  },

  "re-himalayan-452-tubular": {
    ...himalayan452Base,
    descripcion:
      "La Himalayan 452 en su configuración con llantas de rayos tubulares, pensada para mayor resistencia en uso off-road exigente, sobre la misma base Sherpa 450.",
    destacados: himalayanDestacados,
    colores: [],
  },

  "re-himalayan-452-rally": {
    ...himalayan452Base,
    descripcion:
      "La Himalayan 452 Rally es la versión más orientada al off-road de la adventure de 452 cc, con preparación específica para terreno difícil.",
    destacados: himalayanDestacados,
    colores: [],
  },

  "re-classic-650": {
    ...classic650Base,
    descripcion:
      "La Classic 650 lleva el estilo atemporal de la Classic al bicilíndrico de 648 cc: presencia, torque parejo y acabado premium.",
    destacados: [
      "Bicilíndrico de 648 cc, 47 hp",
      "Estética clásica atemporal",
      "Frenos de disco con ABS de doble canal",
      "Doble amortiguador trasero",
      "Acabados premium",
    ],
    colores: [],
  },

  "re-classic-650-chrome": {
    ...classic650Base,
    descripcion:
      "La Classic 650 Chrome suma un acabado íntegramente cromado al bicilíndrico de 648 cc, llevando la presencia y el lujo retro al máximo.",
    destacados: [
      "Bicilíndrico de 648 cc, 47 hp",
      "Acabado íntegramente cromado",
      "Estética clásica atemporal",
      "ABS de doble canal",
      "Doble amortiguador trasero",
    ],
    colores: ["Chrome"],
  },

  "re-shotgun-650": {
    descripcion:
      "La Shotgun 650 es una custom bobber sobre el bicilíndrico de 648 cc: líneas limpias, postura agresiva y suspensión Showa para un andar firme.",
    destacados: [
      "Bicilíndrico de 648 cc, 47 hp",
      "Estilo bobber / custom",
      "Suspensión Showa adelante y atrás",
      "Frenos de disco con ABS de doble canal",
      "Plataforma modular configurable",
    ],
    motor: "Bicilíndrico en paralelo, 4T, SOHC, refrigerado por aire/aceite",
    cilindrada: "648 cc",
    potencia: "47 hp @ 7.250 rpm (34,6 kW)",
    torque: "52,3 Nm @ 5.650 rpm",
    transmision: "6 velocidades",
    frenos: "Disco 320 mm delantero (2 pistones) · Disco 320 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Horquilla invertida Showa, 120 mm",
    suspensionTras: "Doble amortiguador Showa, 90 mm de recorrido",
    neumaticoDel: "100/90-18 (tubeless)",
    neumaticoTras: "150/70 R17 (tubeless)",
    largo: "2.220 mm",
    alturaAsiento: "795 mm",
    // Fuente entregó 428 kg (lectura corrupta) → pendiente de verificación.
    peso: DATO_FALTANTE,
    estanque: "13,8 L",
    colores: ["Plasma Blue", "Stencil White"],
  },

  "re-bear-650": {
    descripcion:
      "La Bear 650 es una scrambler de 648 cc inspirada en la Big Bear Run: más torque (56,5 Nm), rueda de 19'' y actitud todo-terreno con alma retro.",
    destacados: [
      "Bicilíndrico de 648 cc con 56,5 Nm de torque",
      "Estilo scrambler",
      "Tablero TFT circular",
      "ABS de doble canal desconectable atrás",
      "Escape alto scrambler",
    ],
    motor: "Bicilíndrico en línea, 4T, SOHC, refrigerado por aire/aceite",
    cilindrada: "648 cc",
    potencia: "47,4 hp @ 7.150 rpm (34,9 kW)",
    torque: "56,5 Nm @ 5.150 rpm",
    transmision: "6 velocidades, engrane constante",
    frenos: "Disco ventilado 320 mm delantero (2 pistones) · Disco ventilado 270 mm trasero",
    abs: "Doble canal (desconectable atrás)",
    suspensionDel: DATO_FALTANTE,
    suspensionTras: DATO_FALTANTE,
    neumaticoDel: "100/90-19",
    neumaticoTras: "140/80 R17",
    largo: "2.180 mm",
    alturaAsiento: DATO_FALTANTE,
    peso: "216 kg",
    estanque: "13,7 L",
    colores: [],
  },

  "re-super-meteor-650-astral": {
    ...superMeteor650Base,
    descripcion:
      "La Super Meteor 650 Astral es la cruiser de ruta de Royal Enfield en acabado monocolor: bicilíndrico de 648 cc, postura baja y relajada, y horquilla invertida para devorar kilómetros.",
    destacados: [
      "Bicilíndrico de 648 cc, 47 hp",
      "Postura cruiser baja y cómoda",
      "Horquilla invertida de 43 mm",
      "Frenos de disco con ABS de doble canal",
      "Versión Tourer con parabrisas y respaldo",
    ],
    colores: ["Astral Black", "Astral Green", "Astral Blue"],
  },

  "re-super-meteor-650-interestellar": {
    ...superMeteor650Base,
    descripcion:
      "La Super Meteor 650 Interstellar suma esquema bicolor a la cruiser de ruta de 648 cc, con la misma plataforma de postura baja y horquilla invertida.",
    destacados: [
      "Bicilíndrico de 648 cc, 47 hp",
      "Esquema de color bicolor Interstellar",
      "Postura cruiser baja y cómoda",
      "Horquilla invertida de 43 mm",
      "ABS de doble canal",
    ],
    colores: ["Interstellar Green", "Interstellar Grey"],
  },

  "re-super-meteor-650-celestial": {
    ...superMeteor650Base,
    descripcion:
      "La Super Meteor 650 Celestial es la versión tope de gama de la cruiser de ruta de 648 cc, con la mejor terminación de la familia Super Meteor.",
    destacados: [
      "Bicilíndrico de 648 cc, 47 hp",
      "Terminación tope de gama Celestial",
      "Postura cruiser baja y cómoda",
      "Horquilla invertida de 43 mm",
      "ABS de doble canal",
    ],
    colores: ["Celestial Red"],
  },

  // ── SUZUKI ─────────────────────────────────────────────────────────────────
  "sz-burgman-street-125": {
    descripcion: "Scooter urbano 124 cc con sistema de frenos combinados CBS y transmisión CVT automática. La opción más práctica y económica para moverse en la ciudad sin complicaciones.",
    destacados: [
      "Sistema CBS de frenada combinada para mayor seguridad y equilibrio",
      "Transmisión CVT automática: máxima comodidad en tráfico ciudad",
      "Asiento bajo 780 mm accesible para todo tipo de conductores",
      "Estanque de 5,5 L y bajo consumo para el uso diario",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire",
    cilindrada: "124 cc",
    potencia: "—",
    torque: "—",
    transmision: "Automática CVT",
    frenos: "Disco delantero · Tambor trasero",
    abs: "No (CBS)",
    suspensionDel: "Telescópica, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "Basculante, resorte helicoidal, amortiguador de aceite",
    neumaticoDel: "90/90-12 44J, tubeless",
    neumaticoTras: "100/80-12 56J, tubeless",
    largo: "1.860 mm",
    alturaAsiento: "780 mm",
    peso: "115 kg",
    estanque: "5,5 L",
    colores: ["Pearl Grace White", "Metallic Mat Black No.2", "Metallic Mat Stellar Blue"],
  },

  "sz-gsx-150-frf-gixxer": {
    descripcion: "Deportiva carenada 150 cc con diseño agresivo inspirado en las GSX-R y motor air-cooled de 14 HP. La puerta de entrada al mundo sport con economía y estilo.",
    destacados: [
      "Carenado completo de estética deportiva inspirado en la familia GSX-R",
      "Motor 154,9 cc con 14 HP y 14 Nm de torque para conducción ágil",
      "Frenos de disco delantero y trasero para mayor confianza al frenar",
      "Neumáticos 100/80-17 delantero y 140/60R17 trasero para buen agarre",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire",
    cilindrada: "154,9 cc",
    potencia: "14 hp @ 8.000 rpm",
    torque: "14 Nm @ 6.000 rpm",
    transmision: "5 velocidades",
    frenos: "Disco delantero · Disco trasero",
    abs: "—",
    suspensionDel: "Telescópica, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "Basculante, amortiguador monounitario",
    neumaticoDel: "100/80-17, tubeless",
    neumaticoTras: "140/60R17, tubeless",
    largo: "2.050 mm",
    alturaAsiento: "780 mm",
    peso: "139 kg",
    estanque: "12 L",
    colores: [],
  },

  "sz-gsx-150-rf-gixxer": {
    descripcion: "Naked 150 cc ágil y económica con frenos de disco en ambas ruedas y motor de 14 HP. La referencia entry-level en motos sport naked para ciudad y ruta.",
    destacados: [
      "Motor 154 cc air-cooled con 14 HP y diseño naked deportivo",
      "Frenos de disco delantero y trasero para frenada segura",
      "Neumáticos 100/80-17 y 140/60R17 para buen rendimiento en asfalto",
      "Transmisión 5 velocidades y bajo peso para máxima agilidad urbana",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire",
    cilindrada: "154 cc",
    potencia: "14 hp @ 8.000 rpm",
    torque: "14 Nm @ 6.000 rpm",
    transmision: "5 velocidades",
    frenos: "Disco delantero · Disco trasero",
    abs: "—",
    suspensionDel: "Telescópica, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "—",
    neumaticoDel: "100/80-17M/C 52S",
    neumaticoTras: "140/60R17M/C 63H",
    largo: "2.020 mm",
    alturaAsiento: "—",
    peso: "139 kg",
    estanque: "—",
    colores: [],
  },

  "sz-gsx250fi-gixxer": {
    descripcion: "Deportiva carenada 250 cc con motor oil-cooled de inyección electrónica y 26 HP. La Gixxer SF 250 lleva el espíritu GSX-R al cuarto de litro con prestaciones reales.",
    destacados: [
      "Motor 249 cc oil-cooled SOHC con inyección electrónica y 26 HP",
      "22 Nm de torque disponibles desde bajas RPM para conducción dinámica",
      "Neumáticos radiales 110/70R17 delantero y 150/60R17 trasero",
      "Transmisión de 6 velocidades para aprovechar el motor en ruta y ciudad",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aceite",
    cilindrada: "249 cc",
    potencia: "26 hp @ 9.000 rpm",
    torque: "22 Nm @ 7.300 rpm",
    transmision: "6 velocidades",
    frenos: "Disco delantero · Disco trasero",
    abs: "—",
    suspensionDel: "—",
    suspensionTras: "—",
    neumaticoDel: "110/70R17M/C 54H",
    neumaticoTras: "150/60R17M/C 66H",
    largo: "2.010 mm",
    alturaAsiento: "—",
    peso: "158 kg",
    estanque: "—",
    colores: [],
  },

  "sz-gsx250di-gixxer": {
    descripcion: "Naked 250 cc con motor oil-cooled de inyección electrónica y 26 HP en un paquete ágil y moderno. La Gixxer 250 ofrece prestaciones de cuarto de litro para ciudad y ruta.",
    destacados: [
      "Motor 249 cc oil-cooled FI con 26 HP y 22 Nm para máxima versatilidad",
      "Diseño naked deportivo con neumáticos radiales de alto rendimiento",
      "110/70R17 delantero y 150/60R17 trasero para mayor agarre y estabilidad",
      "6 velocidades para aprovechar el motor en todo el rango de RPM",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aceite",
    cilindrada: "249 cc",
    potencia: "26 hp @ 9.000 rpm",
    torque: "22 Nm @ 7.300 rpm",
    transmision: "6 velocidades",
    frenos: "Disco delantero · Disco trasero",
    abs: "—",
    suspensionDel: "—",
    suspensionTras: "—",
    neumaticoDel: "110/70R17M/C 54H",
    neumaticoTras: "150/60R17M/C 66H",
    largo: "2.010 mm",
    alturaAsiento: "—",
    peso: "154 kg",
    estanque: "—",
    colores: [],
  },

  "sz-gsx-8s": {
    descripcion: "Naked bicilíndrica 776 cc con 83 HP, ABS doble canal y control de tracción de serie. El equilibrio perfecto entre potencia callejera, manejabilidad y electrónica avanzada.",
    destacados: [
      "Motor 776 cc parallel-twin DOHC con 83 HP y 78 Nm de torque",
      "ABS doble canal + control de tracción de serie en todas las versiones",
      "Horquilla invertida con frenos Nissin 4 pistones y discos de 310 mm",
      "Peso de 202 kg: fácil de maniobrar en ciudad, exigente en ruta",
      "Pantalla TFT a color con conectividad y múltiples modos de conducción",
    ],
    motor: "Bicilíndrico en paralelo, 4T, DOHC, refrigerado por líquido",
    cilindrada: "776 cc",
    potencia: "83 hp @ 8.500 rpm",
    torque: "78 Nm @ 6.800 rpm",
    transmision: "6 velocidades",
    frenos: "2× Disco 310 mm delantero (4 pistones) · Disco 240 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica invertida, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "Basculante con monoamortiguador tipo link, resorte helicoidal",
    neumaticoDel: "120/70ZR17M/C (58W), tubeless",
    neumaticoTras: "180/55ZR17M/C (73W), tubeless",
    largo: "2.115 mm",
    alturaAsiento: "810 mm",
    peso: "202 kg",
    estanque: "14 L",
    colores: ["Candy Daring Red / Metallic Matte Black No.2", "Metallic Matte Black No.2 / Glass Sparkle Black"],
  },

  "sz-gsx-s1000": {
    descripcion: "Naked 999 cc de alto rendimiento con motor de herencia GSX-R, frenos Brembo Monobloc y horquilla KYB totalmente ajustable. Para el piloto que exige el máximo sin renunciar a la versatilidad callejera.",
    destacados: [
      "Motor 999 cc 4 cilindros en línea con 150 HP heredado directamente de la GSX-R",
      "Frenos Brembo Monobloc 4 pistones, discos 310 mm dobles, ABS doble canal",
      "Horquilla KYB totalmente ajustable y amortiguador Showa BFRC",
      "Control de tracción + 3 modos de potencia + quickshifter bi-direccional",
      "Estanque de 19 L para salidas largas de ruta sin interrupciones",
    ],
    motor: "Tetracilíndrico en línea, 4T, DOHC, refrigerado por líquido",
    cilindrada: "999 cc",
    potencia: "149,9 hp @ 11.000 rpm",
    torque: "106 Nm @ 9.250 rpm",
    transmision: "6 velocidades",
    frenos: "2× Disco 310 mm delantero (4 pistones Brembo) · Disco 240 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica invertida KYB, totalmente ajustable",
    suspensionTras: "Basculante con monoamortiguador Showa BFRC tipo link, totalmente ajustable",
    neumaticoDel: "120/70ZR17M/C (58W), tubeless",
    neumaticoTras: "190/50ZR17M/C (73W), tubeless",
    largo: "2.115 mm",
    alturaAsiento: "810 mm",
    peso: "214 kg",
    estanque: "19 L",
    colores: ["Metallic Matte Sword Silver", "Glass Sparkle Black"],
  },

  "sz-gsx-r1000r": {
    descripcion: "Superbike 999 cc de competición con 192 HP, sistema IMU de 6 ejes y suspensión Showa Balance Free. El tope de gama deportivo de Suzuki, directamente derivado del Mundial de Superbike.",
    destacados: [
      "192 HP con electrónica de nivel MotoGP: IMU, TC de inclinación, ABS lean-sensitive",
      "Suspensión Showa BFF delantera y BFRC trasera exclusiva de superbike",
      "Frenos Brembo radiales de alta performance con ABS conmutable",
      "Motor GSX-R 999 cc con válvulas de titanio e inyección de doble estrangulador",
      "202 kg en orden de marcha: el peso más bajo en su clase de potencia",
    ],
    motor: "Tetracilíndrico en línea, 4T, DOHC, refrigerado por líquido",
    cilindrada: "999,8 cc",
    potencia: "192,4 hp @ 13.200 rpm",
    torque: "110 Nm @ 11.000 rpm",
    transmision: "6 velocidades",
    frenos: "2× Disco delantero (Brembo radial) · Disco trasero",
    abs: "Doble canal, lean-sensitive, conmutable",
    suspensionDel: "Telescópica invertida Showa BFF (Balance Free Fork), totalmente ajustable",
    suspensionTras: "Basculante con monoamortiguador Showa BFRC-lite tipo link, totalmente ajustable",
    neumaticoDel: "120/70ZR17M/C (58W), tubeless",
    neumaticoTras: "190/55ZR17M/C (75W), tubeless",
    largo: "2.075 mm",
    alturaAsiento: "825 mm",
    peso: "202 kg",
    estanque: "16 L",
    colores: ["Candy Daring Red / Glass Sparkle Black", "Metallic Matte Sword Silver"],
  },

  "sz-gsx1300ra-hayabusa": {
    descripcion: "El hipersport definitivo: 1.340 cc, ~190 HP y una silueta icónica reconocida en todo el mundo. Electrónica de última generación con frenos Brembo Stylema y ABS Motion Track.",
    destacados: [
      "Motor 1.340 cc 4 cilindros con ~190 HP y diseño aerodinámico sin igual",
      "Frenos Brembo Stylema 4 pistones, discos 320 mm con ABS Motion Track de serie",
      "Electrónica completa: TC con IMU, cruise control adaptativo, quickshifter bi-direccional",
      "Suspensión KYB totalmente ajustable delantera y trasera",
      "Estanque de 20 L para grandes travesías a alta velocidad",
    ],
    motor: "Tetracilíndrico en línea, 4T, DOHC, refrigerado por líquido",
    cilindrada: "1.340 cc",
    potencia: "~190 hp @ 9.700 rpm",
    torque: "~150 Nm @ 7.000 rpm",
    transmision: "6 velocidades",
    frenos: "2× Disco 320 mm delantero (4 pistones Brembo Stylema) · Disco 260 mm trasero",
    abs: "Doble canal (Motion Track ABS)",
    suspensionDel: "Telescópica invertida KYB, totalmente ajustable",
    suspensionTras: "Basculante con monoamortiguador KYB tipo link, totalmente ajustable",
    neumaticoDel: "120/70ZR17M/C (58W), tubeless",
    neumaticoTras: "190/50ZR17M/C (73W), tubeless",
    largo: "2.180 mm",
    alturaAsiento: "800 mm",
    peso: "264 kg",
    estanque: "20 L",
    colores: ["Candy Daring Red / Glass Sparkle Black", "Pearl Vigor Blue / Pearl Brilliant White"],
  },

  "sz-vstrom-ds250-sx": {
    descripcion: "Adventure 250 cc monocilíndrica con suspensión de recorrido generoso, neumáticos trail y 26 HP de inyección electrónica. El ADN V-Strom en formato cuarto de litro para exploración mixta.",
    destacados: [
      "Motor 249 cc oil-cooled SOHC FI con 26,1 HP y 22,2 Nm de torque",
      "205 mm de despeje al suelo para superar terrenos irregulares sin problemas",
      "Neumáticos adventure 100/90-19 delantero y 140/70-17 trasero",
      "ABS doble canal de serie para mayor seguridad en cualquier superficie",
      "167 kg y asiento de 835 mm para buen dominio y control del piloto",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aceite",
    cilindrada: "249 cc",
    potencia: "26,1 hp @ 9.300 rpm",
    torque: "22,2 Nm @ 7.300 rpm",
    transmision: "6 velocidades",
    frenos: "Disco delantero · Disco trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "Basculante, resorte helicoidal, amortiguador de aceite",
    neumaticoDel: "100/90-19M/C 57S, tubeless",
    neumaticoTras: "140/70-17M/C 66S, tubeless",
    largo: "2.180 mm",
    alturaAsiento: "835 mm",
    peso: "167 kg",
    estanque: "12 L",
    colores: [
      "Pearl Fresh Blue / Glass Sparkle Black",
      "Champion Yellow No.2 / Glass Sparkle Black",
      "Pearl Glacier White / Met Mat Stellar Blue",
      "Glass Sparkle Black",
    ],
  },

  "sz-vstrom-dl650xa": {
    descripcion: "Adventure V-twin 645 cc mundialmente reconocida por su versatilidad y confiabilidad. ABS doble canal y neumáticos todoterreno para touring, ruta y gravel con total comodidad.",
    destacados: [
      "Motor V-twin 645 cc con gran torque en todo el rango para conducción versátil",
      "ABS doble canal con suspensión delantera telescópica 43 mm ajustable",
      "Neumáticos 110/80-19 delantero y 150/70-17 trasero para off-road moderado",
      "Estanque de 20 L: autonomía excepcional para viajes de larga distancia",
      "Posición erguida ergonómica ideal para ciudad, ruta y ripio",
    ],
    motor: "Bicilíndrico en V 90°, 4T, DOHC, refrigerado por líquido",
    cilindrada: "645 cc",
    potencia: "—",
    torque: "—",
    transmision: "6 velocidades",
    frenos: "2× Disco 310 mm delantero (2 pistones) · Disco 260 mm trasero",
    abs: "Doble canal",
    suspensionDel: "Telescópica 43 mm, resorte helicoidal, amortiguador de aceite (ajustable precarga)",
    suspensionTras: "Basculante con monoamortiguador tipo link (ajustable rebote)",
    neumaticoDel: "110/80R19 M/C (59V), tubeless",
    neumaticoTras: "150/70R17 M/C (69V), tubeless",
    largo: "2.275 mm",
    alturaAsiento: "835 mm",
    peso: "213 kg",
    estanque: "20 L",
    colores: ["Glass Sparkle Black"],
  },

  "sz-vstrom-dl800-de": {
    descripcion: "Adventure twin 776 cc con 83 HP y 220 mm de recorrido de suspensión. ABS conmutable y neumáticos enduro para quienes no se conforman con el asfalto.",
    destacados: [
      "Motor 776 cc parallel-twin DOHC con 83 HP y 220 mm de recorrido de suspensión",
      "ABS conmutable: desactiva el ABS trasero para off-road real",
      "Neumáticos con tubo 90/90-21 delantero y 150/70-17 trasero de perfil enduro",
      "Doble propósito real: deportivo en asfalto, capaz en grava y ripio",
      "Estanque de 20 L para expediciones de larga distancia sin límites",
    ],
    motor: "Bicilíndrico en paralelo, 4T, DOHC, refrigerado por líquido",
    cilindrada: "776 cc",
    potencia: "83 hp @ 8.500 rpm",
    torque: "78 Nm @ 6.800 rpm",
    transmision: "6 velocidades",
    frenos: "2× Disco 310 mm delantero (2 pistones) · Disco 260 mm trasero",
    abs: "Doble canal, conmutable",
    suspensionDel: "Telescópica invertida Showa, resorte helicoidal, 220 mm recorrido",
    suspensionTras: "Basculante con monoamortiguador Showa tipo link, 220 mm recorrido",
    neumaticoDel: "90/90-21M/C (54H), con tubo",
    neumaticoTras: "150/70R17 M/C (69H), con tubo",
    largo: "2.345 mm",
    alturaAsiento: "855 mm",
    peso: "230 kg",
    estanque: "20 L",
    colores: ["Champion Yellow No.2", "Glass Sparkle Black"],
  },

  "sz-vstrom-dl1050-de": {
    descripcion: "La adventure tourer V-twin 1.037 cc de Suzuki con electrónica completa y suspensión de largo recorrido. Preparada para expediciones de larga distancia en cualquier tipo de terreno.",
    destacados: [
      "Motor V-twin 1.037 cc con ABS Motion Track y múltiples modos de conducción",
      "Control de tracción ajustable con sensor IMU para máxima seguridad activa",
      "Suspensión de largo recorrido con neumáticos 90/90-21 con tubo para off-road",
      "Estanque de 20 L y amplia ergonomía para travesías de múltiples días",
      "El adventure tourer V-twin de mayor cilindrada del catálogo Suzuki",
    ],
    motor: "Bicilíndrico en V 90°, 4T, DOHC, refrigerado por líquido",
    cilindrada: "1.037 cc",
    potencia: "—",
    torque: "—",
    transmision: "6 velocidades",
    frenos: "2× Disco 310 mm delantero (4 pistones) · Disco 260 mm trasero (2 pistones)",
    abs: "Doble canal, conmutable (Motion Track ABS)",
    suspensionDel: "Telescópica invertida, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "Basculante con monoamortiguador tipo link, ajustable",
    neumaticoDel: "90/90-21 M/C (54H), con tubo",
    neumaticoTras: "150/70R17 M/C (69H), tubeless",
    largo: "2.390 mm",
    alturaAsiento: "880 mm",
    peso: "252 kg",
    estanque: "20 L",
    colores: ["Pearl Tech White / Glass Sparkle Black"],
  },

  "sz-dr125l": {
    descripcion: "Trail de iniciación 124 cc ultra-liviana con apenas 89 kg en orden de marcha. La primera moto off-road ideal para jóvenes y principiantes que quieren aprender técnica de terreno.",
    destacados: [
      "Solo 89 kg en orden de marcha: la trail más ligera del catálogo Suzuki",
      "Freno de disco delantero para control confiable en terrenos técnicos",
      "Suspensión delantera telescópica y basculante trasero tipo link",
      "Neumáticos trail 70/100-19 delantero y 90/100-16 trasero",
      "Transmisión 5 velocidades manual para aprendizaje progresivo del terreno",
    ],
    motor: "Monocilíndrico, 4T, SOHC, refrigerado por aire",
    cilindrada: "124 cc",
    potencia: "—",
    torque: "—",
    transmision: "5 velocidades",
    frenos: "Disco delantero · Tambor trasero",
    abs: "—",
    suspensionDel: "Telescópica, resorte helicoidal, amortiguador de aceite",
    suspensionTras: "Basculante tipo link, resorte helicoidal, amortiguador de aceite",
    neumaticoDel: "70/100-19 M/C 42M, con tubo",
    neumaticoTras: "90/100-16 M/C 52M, con tubo",
    largo: "1.885 mm",
    alturaAsiento: "805 mm",
    peso: "89 kg",
    estanque: "4,8 L",
    colores: ["Champion Yellow No.2"],
  },

  "sz-rmz250": {
    descripcion: "Motocross 249 cc de competición con motor DOHC líquido y suspensión completamente ajustable. Lista para los circuitos de tierra más exigentes a nivel amateur y profesional.",
    destacados: [
      "Motor 249 cc DOHC refrigerado por líquido con potencia enfocada en competición",
      "Horquilla invertida y mono trasero completamente ajustables en compresión y rebote",
      "Frenos de disco delantero y trasero para frenada de alto rendimiento en pista",
      "Solo 106 kg: relación potencia-peso excepcional para dominar en circuito",
      "Transmisión 5 velocidades diseñada para rendimiento máximo en tierra",
    ],
    motor: "Monocilíndrico, 4T, DOHC, refrigerado por líquido",
    cilindrada: "249 cc",
    potencia: "—",
    torque: "—",
    transmision: "5 velocidades",
    frenos: "Disco delantero · Disco trasero",
    abs: "—",
    suspensionDel: "Telescópica invertida, totalmente ajustable (compresión y rebote)",
    suspensionTras: "Basculante con monoamortiguador tipo link, totalmente ajustable",
    neumaticoDel: "80/100-21 M/C (51M), con tubo",
    neumaticoTras: "100/90-19 M/C (57M), con tubo",
    largo: "2.185 mm",
    alturaAsiento: "955 mm",
    peso: "106 kg",
    estanque: "6,3 L",
    colores: ["Champion Yellow No.2"],
  },

  "sz-rmz450": {
    descripcion: "Motocross 449 cc de alto rendimiento con suspensión Showa Balance Free y frenos de competición. Para el piloto que exige el máximo desempeño en los circuitos de tierra profesionales.",
    destacados: [
      "Motor 449 cc DOHC líquido: potencia de élite para motocross de alto nivel",
      "Suspensión Showa BFF delantera y BFRC trasera de competición mundial",
      "Disco delantero 270 mm con caliper de 2 pistones para frenada precisa",
      "Solo 112 kg de peso: herramienta afilada para ganar en pista",
      "Transmisión 5 velocidades para máxima aceleración y control en tierra",
    ],
    motor: "Monocilíndrico, 4T, DOHC, refrigerado por líquido",
    cilindrada: "449 cc",
    potencia: "—",
    torque: "—",
    transmision: "5 velocidades",
    frenos: "Disco 270 mm delantero (2 pistones) · Disco trasero",
    abs: "—",
    suspensionDel: "Telescópica invertida Showa BFF (Balance Free Fork), totalmente ajustable",
    suspensionTras: "Basculante con monoamortiguador Showa BFRC tipo link, totalmente ajustable",
    neumaticoDel: "80/100-21 M/C (51M), con tubo",
    neumaticoTras: "110/90-19 M/C (62M), con tubo",
    largo: "2.175 mm",
    alturaAsiento: "960 mm",
    peso: "112 kg",
    estanque: "6,3 L",
    colores: ["Champion Yellow No.2"],
  },

  "sz-ltf-400-fsm3": {
    descripcion: "ATV 4×4 376 cc con selección 2WD/4WD, transmisión 5 velocidades y tracción por cardán. Resistente y económico para trabajo agrícola y recreación fuera de ruta.",
    destacados: [
      "Motor 376 cc air-cooled con selección de tracción 2WD/4WD en movimiento",
      "Transmisión 5 velocidades con alta, baja y marcha atrás para cualquier terreno",
      "Tracción total por cardán: sin cadena que mantener ni ajustar",
      "Frenos de disco dobles delanteros y tambor trasero sellado",
      "Diseño compacto y maniobrable para trabajo en campo y recreación",
    ],
    motor: "Monocilíndrico, 4T, OHC, refrigerado por aire (SCAS)",
    cilindrada: "376 cc",
    potencia: "—",
    torque: "—",
    transmision: "5 velocidades (H/L/Retroceso), cardán",
    frenos: "Disco doble delantero · Tambor trasero",
    abs: "—",
    suspensionDel: "Doble triángulo independiente, resorte helicoidal",
    suspensionTras: "Basculante, resorte helicoidal",
    neumaticoDel: "AT25×8-12, tubeless",
    neumaticoTras: "AT25×10-12, tubeless",
    largo: "2.060 mm",
    alturaAsiento: "840 mm",
    peso: "279 kg",
    estanque: "16 L",
    colores: ["Terra Green", "Flame Red"],
  },

  "sz-lta-900xpm3": {
    descripcion: "ATV 4×4 493 cc con transmisión CVT Quadmatic, diferencial bloqueante y dirección asistida eléctrica. Potencia y tracción total para los trabajos y terrenos más exigentes.",
    destacados: [
      "Motor 493 cc líquido OHC con CVT Quadmatic y diferencial bloqueante",
      "Tracción total 4WD con diferencial delantero bloqueante para máxima adherencia",
      "Dirección asistida eléctrica (EPS) para reducir la fatiga en terrenos difíciles",
      "Suspensión independiente doble triángulo con gas en las 4 ruedas",
      "Frenos de disco dobles delanteros y disco múltiple en baño de aceite trasero",
    ],
    motor: "Monocilíndrico, 4T, OHC, refrigerado por líquido",
    cilindrada: "493 cc",
    potencia: "—",
    torque: "—",
    transmision: "CVT Quadmatic (H/L/Retroceso), cardán, diferencial bloqueante",
    frenos: "Disco doble delantero · Disco múltiple en baño de aceite trasero",
    abs: "—",
    suspensionDel: "Doble triángulo independiente, resorte helicoidal, amortiguador a gas",
    suspensionTras: "Doble triángulo independiente, resorte helicoidal, amortiguador a gas",
    neumaticoDel: "AT25×8-12, tubeless",
    neumaticoTras: "AT25×10-12, tubeless",
    largo: "2.150 mm",
    alturaAsiento: "920 mm",
    peso: "324 kg",
    estanque: "17,5 L",
    colores: ["Desert Beige", "Terra Green", "Flame Red"],
  },

  "sz-lta-750xpm3": {
    descripcion: "ATV 4×4 722 cc DOHC con transmisión CVT y Power Steering eléctrico. El cuádruple de mayor cilindrada de Suzuki, diseñado para los trabajos y exploraciones más demandantes.",
    destacados: [
      "Motor DOHC 722 cc líquido: el ATV más potente del catálogo Suzuki",
      "CVT Quadmatic con 2WD, 4WD y bloqueo diferencial para máxima tracción",
      "Dirección asistida eléctrica (EPS) para manejo sin fatiga en terrenos duros",
      "Suspensión independiente doble triángulo con gas en las 4 ruedas",
      "Frenos de disco dobles delanteros y disco múltiple en baño de aceite trasero",
    ],
    motor: "Monocilíndrico, 4T, DOHC, refrigerado por líquido",
    cilindrada: "722 cc",
    potencia: "—",
    torque: "—",
    transmision: "CVT Quadmatic (H/L/Retroceso), cardán, diferencial bloqueante",
    frenos: "Disco doble delantero · Disco múltiple en baño de aceite trasero",
    abs: "—",
    suspensionDel: "Doble triángulo independiente, resorte helicoidal, amortiguador a gas",
    suspensionTras: "Doble triángulo independiente, resorte helicoidal, amortiguador a gas",
    neumaticoDel: "AT25×8-12, tubeless",
    neumaticoTras: "AT25×10-12, tubeless",
    largo: "2.150 mm",
    alturaAsiento: "920 mm",
    peso: "329 kg",
    estanque: "17,5 L",
    colores: ["Terra Green", "Flame Red", "Desert Beige"],
  },
};
